### ISSUE TITLE
Possible issue Chrome 90 / WebRTC

### ISSUE THREAD

**Issue by k0nr4d** [ant-media/Ant-Media-Server#3182]
### Short description
The example streaming system at https://DOMAIN.COM:5443/WebRTCAppEE/ has stopped working after updating from Chrome 89 to Chrome 90 on both Windows 10 and Mac OSX. Errors out after pressing publish with an alert() that says "WebSocket Connection is disconnected."

### Environment
* Operating system and version: Windows 10 + Mac OSX
* Ant Media Server version: 2.3.0 and 2.3.1 enterprise.
* Browser name and version: Chrome 89 vs Chrome 90

### Steps to reproduce
1.  Try /WebRTCAppEE/ streaming example using Chrome 89
2.  Update to Chrome 90
3.  Stops working

### Actual behavior
I have tested this on 6 different Antmedia 2.3.0 / 2.3.1 servers which are live in production, and we have been able to recreate it on 3 separate computers connected to 3 separate networks. One had Chrome 89 - it worked fine, updated it to Chrome 90 and it broke. Version 90.0.4430.85 (Official Build) (64-bit)

Works on Safari, Firefox on Mac and Firefox on PC. Issue seems to be limited to Chrome.  

MAY have something to do with this:
var path =  location.hostname + ":" + location.port + appName + "websocket?rtmpForward=" + rtmpForward;
var websocketURL =  "ws://" + path;

On our apps which are still working under chrome 90, we do not include the ?rtmpForward part.

### Logs
Console Log:
websocket connected
(index):451 initialized
websocket_adaptor.js:19 websocket connected
(index):451 initialized
websocket_adaptor.js:136 sent message:{"command":"publish","streamId":"stream1","video":true,"audio":true}
webrtc_adaptor.js:1042 stream id in init peer connection: stream1 close stream id: stream1
webrtc_adaptor.js:1163 Set local description successfully for stream Id stream1
websocket_adaptor.js:136 sent message:{"command":"takeConfiguration","streamId":"stream1","type":"offer","sdp":"v=0\r\no=- 3728299439370192602 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2 3\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS 66259d4a-7ec0-4323-b834-f3a11a7e8aaf\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:odrr\r\na=ice-pwd:MJalacXWFgDm5uKxIxi2GNAR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 00:17:0F:8A:7D:06:2C:96:90:AB:15:61:B5:94:7A:86:C2:6F:84:63:C6:52:D6:A7:20:8D:41:EE:B4:33:C7:AD\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 066d4822-8a79-42a2-860b-d1371e56d43e\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:3010961839 cname:dmXhQoa/lxxSWEMh\r\na=ssrc:3010961839 msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 066d4822-8a79-42a2-860b-d1371e56d43e\r\na=ssrc:3010961839 mslabel:66259d4a-7ec0-4323-b834-f3a11a7e8aaf\r\na=ssrc:3010961839 label:066d4822-8a79-42a2-860b-d1371e56d43e\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:odrr\r\na=ice-pwd:MJalacXWFgDm5uKxIxi2GNAR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 00:17:0F:8A:7D:06:2C:96:90:AB:15:61:B5:94:7A:86:C2:6F:84:63:C6:52:D6:A7:20:8D:41:EE:B4:33:C7:AD\r\na=setup:actpass\r\na=mid:1\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 67f23087-ce68-4cea-ba7e-d8f510465c6e\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:4064907437 cname:dmXhQoa/lxxSWEMh\r\na=ssrc:4064907437 msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 67f23087-ce68-4cea-ba7e-d8f510465c6e\r\na=ssrc:4064907437 mslabel:66259d4a-7ec0-4323-b834-f3a11a7e8aaf\r\na=ssrc:4064907437 label:67f23087-ce68-4cea-ba7e-d8f510465c6e\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123 118 114 115 116\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:odrr\r\na=ice-pwd:MJalacXWFgDm5uKxIxi2GNAR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 00:17:0F:8A:7D:06:2C:96:90:AB:15:61:B5:94:7A:86:C2:6F:84:63:C6:52:D6:A7:20:8D:41:EE:B4:33:C7:AD\r\na=setup:actpass\r\na=mid:2\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 7487094b-714c-4727-8111-639d638a32cc\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:35 AV1X/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:124 H264/90000\r\na=rtcp-fb:124 goog-remb\r\na=rtcp-fb:124 transport-cc\r\na=rtcp-fb:124 ccm fir\r\na=rtcp-fb:124 nack\r\na=rtcp-fb:124 nack pli\r\na=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f\r\na=rtpmap:119 rtx/90000\r\na=fmtp:119 apt=124\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 transport-cc\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f\r\na=rtpmap:118 rtx/90000\r\na=fmtp:118 apt=123\r\na=rtpmap:114 red/90000\r\na=rtpmap:115 rtx/90000\r\na=fmtp:115 apt=114\r\na=rtpmap:116 ulpfec/90000\r\na=ssrc-group:FID 2015544698 2202179698\r\na=ssrc:2015544698 cname:dmXhQoa/lxxSWEMh\r\na=ssrc:2015544698 msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 7487094b-714c-4727-8111-639d638a32cc\r\na=ssrc:2015544698 mslabel:66259d4a-7ec0-4323-b834-f3a11a7e8aaf\r\na=ssrc:2015544698 label:7487094b-714c-4727-8111-639d638a32cc\r\na=ssrc:2202179698 cname:dmXhQoa/lxxSWEMh\r\na=ssrc:2202179698 msid:66259d4a-7ec0-4323-b834-f3a11a7e8aaf 7487094b-714c-4727-8111-639d638a32cc\r\na=ssrc:2202179698 mslabel:66259d4a-7ec0-4323-b834-f3a11a7e8aaf\r\na=ssrc:2202179698 label:7487094b-714c-4727-8111-639d638a32cc\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:odrr\r\na=ice-pwd:MJalacXWFgDm5uKxIxi2GNAR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 00:17:0F:8A:7D:06:2C:96:90:AB:15:61:B5:94:7A:86:C2:6F:84:63:C6:52:D6:A7:20:8D:41:EE:B4:33:C7:AD\r\na=setup:actpass\r\na=mid:3\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":0,"id":"0","candidate":"candidate:1779719387 1 udp 2122260223 192.168.0.186 54224 typ host generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":1,"id":"1","candidate":"candidate:1779719387 1 udp 2122260223 192.168.0.186 54225 typ host generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":2,"id":"2","candidate":"candidate:1779719387 1 udp 2122260223 192.168.0.186 54226 typ host generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":3,"id":"3","candidate":"candidate:1779719387 1 udp 2122260223 192.168.0.186 54227 typ host generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":0,"id":"0","candidate":"candidate:613916715 1 tcp 1518280447 192.168.0.186 9 typ host tcptype active generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":1,"id":"1","candidate":"candidate:613916715 1 tcp 1518280447 192.168.0.186 9 typ host tcptype active generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":2,"id":"2","candidate":"candidate:613916715 1 tcp 1518280447 192.168.0.186 9 typ host tcptype active generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:136 sent message:{"command":"takeCandidate","streamId":"stream1","label":3,"id":"3","candidate":"candidate:613916715 1 tcp 1518280447 192.168.0.186 9 typ host tcptype active generation 0 ufrag odrr network-id 1"}
websocket_adaptor.js:102 connection closed.
(index):493 Connecton closed: {"isTrusted":true}
(index):661 error callback: "WebSocketNotConnected"

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by k0nr4d** [comment]
Update - rtmp_foward has no effect, ignore that BUT

/WebRTCAppEE/publish_with_timestamp.html
This one works fine on all tested computers.

**Comment by k0nr4d** [comment]
/WebRTCAppEE/webrtc-test-tool.html also fails with same error

Working console log from publish_with_timestamp.html
https://pastebin.com/Cw3bQrBH

Failed console log from index.html 
https://pastebin.com/STirVFPH

**Comment by mekya** [comment]
Thank you for the report. 

It was fixed yesterday -> https://github.com/ant-media/Ant-Media-Server/issues/3164

You can get the latest snapshot from your account at antmedia.io and changes in latest snapshot is available here
https://antmedia.io/latest-snapshot

**Comment by k0nr4d** [comment]
I confirm this is resolved in 2.3.2

**Comment by Nyceane** [comment]
@k0nr4d, can i see a test?  As I am still encountering this problem

@mekya, problem still persist, just updated server to 2.3.2 and i am still encountering the problem

<img width="1345" alt="Screen Shot 2021-04-27 at 2 04 03 PM" src="https://user-images.githubusercontent.com/271430/116314579-22f54680-a764-11eb-995e-1304f9317b59.png">


<img width="1680" alt="Screen_Shot_2021-04-27_at_5 01 23_PM" src="https://user-images.githubusercontent.com/271430/116314533-1113a380-a764-11eb-86a6-204fa96df14e.png">

**Comment by mekya** [comment]
Hi @Nyceane ,

I've already answered your question in this issue #3164

Let's proceed in single thread #3164
