### ISSUE TITLE
[Android] If device rotated, during broadcasting, websocket connection is disconnected

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4462]
### Steps to reproduce
1. Open ScreenCaptureActivity
2. Start broadcasting
3. Rotate device

### Expected behavior
Continue to broadcasting

### Actual behavior
Broadcasting disconnected
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
I think we've fixed this issue. Just add the `android:configChanges` to the Activity in Manifest file
```xml

<activity android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|keyboard|screenSize">

```

**Comment by shibupanda** [comment]
@mekya @mustafaboleken issue is still there. attaching logcat.
[disconnect.txt](https://github.com/ant-media/Ant-Media-Server/files/9867063/disconnect.txt)

**Comment by mekya** [comment]
I think we just need to add another option for the `configChanges`. What's your device so that we can test on that device directly? @shibupanda

**Comment by shibupanda** [comment]
I don't think it's device specific.
Mostly for most of the devices it is happening sometimes it's very quick (reproduced in 1st iteration ) sometimes taking 2-3 iteration to reproduce.

Devices we are using:
Samsung A72 12.0.0
Galaxu F12 11.0.0
google pixel 4a 13.0.0

@mekya

**Comment by mekya** [comment]
Hi @shibupanda ,

Thank you for letting us know. Let us test with devices on AWS Device farm and try to reproduce the problem.
